language: node_js
node_js:
  - "4"
  - "5"
  - "6"

branches:
  only:
    - master

before_install:
  - npm install -g istanbul
  - npm install -g mocha

script:
  - istanbul cover _mocha -- -R spec tests/

services:
  - mongodb
