language: node_js
node_js:
  - "4"
  - "5"
  - "6"

branches:
  only:
    - master

before_install:
  - npm install -g istanbul
  - npm install -g mocha

script:
  - istanbul cover _mocha --report lcovonly -- -R spec tests/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

services:
  - mongodb
